name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: deploy
      uses: crazy-max/ghaction-github-pages@v1.2.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      with:
        target_branch: master
        build_dir: public
        committer_name: ewgenius
        committer_email: ewgeniux@gmail.com
        commit_message: CI update
        fqdn: resume.ewgenius.me
